// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use parol_runtime::once_cell::sync::Lazy;
#[allow(unused_imports)]
use parol_runtime::parser::{LLKParser, LookaheadDFA, ParseTreeType, ParseType, Production, Trans};
use parol_runtime::{ParolError, ParseTree};
use parol_runtime::{TokenStream, Tokenizer};
use std::cell::RefCell;
use std::path::Path;

use crate::la_dfa_2_dot_grammar::LaDfa2DotGrammar;
use crate::la_dfa_2_dot_grammar_trait::LaDfa2DotGrammarAuto;

use parol_runtime::lexer::tokenizer::{
    ERROR_TOKEN, NEW_LINE_TOKEN, UNMATCHABLE_TOKEN, WHITESPACE_TOKEN,
};

pub const TERMINALS: &[&str; 25] = &[
    /*  0 */ UNMATCHABLE_TOKEN,
    /*  1 */ UNMATCHABLE_TOKEN,
    /*  2 */ UNMATCHABLE_TOKEN,
    /*  3 */ UNMATCHABLE_TOKEN,
    /*  4 */ UNMATCHABLE_TOKEN,
    /*  5 */ r###"LookaheadDFA"###,
    /*  6 */ r###"\{"###,
    /*  7 */ r###"\}"###,
    /*  8 */ r###"-?\d+"###,
    /*  9 */ r###"/\*"###,
    /* 10 */ r###"\-"###,
    /* 11 */ r###"\*/"###,
    /* 12 */ r###"prod0"###,
    /* 13 */ r###":"###,
    /* 14 */ r###","###,
    /* 15 */ r###"transitions"###,
    /* 16 */ r###"\&"###,
    /* 17 */ r###"\["###,
    /* 18 */ r###"\]"###,
    /* 19 */ r###"Trans"###,
    /* 20 */ r###"\("###,
    /* 21 */ r###"\)"###,
    /* 22 */ r###"k"###,
    /* 23 */ r###""\w+?""###,
    /* 24 */ ERROR_TOKEN,
];

pub const TERMINAL_NAMES: &[&str; 25] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "LookaheadDFA",
    /*  6 */ "LBrace",
    /*  7 */ "RBrace",
    /*  8 */ "Integer",
    /*  9 */ "SlashStar",
    /* 10 */ "Minus",
    /* 11 */ "StarSlash",
    /* 12 */ "Prod0",
    /* 13 */ "Colon",
    /* 14 */ "Comma",
    /* 15 */ "Transitions",
    /* 16 */ "Amp",
    /* 17 */ "LBracket",
    /* 18 */ "RBracket",
    /* 19 */ "Trans",
    /* 20 */ "LParen",
    /* 21 */ "RParen",
    /* 22 */ "K",
    /* 23 */ "NtName",
    /* 24 */ "Error",
];

/* SCANNER_0: "INITIAL" */
const SCANNER_0: (&[&str; 5], &[usize; 19]) = (
    &[
        /*  0 */ UNMATCHABLE_TOKEN,
        /*  1 */ NEW_LINE_TOKEN,
        /*  2 */ WHITESPACE_TOKEN,
        /*  3 */ r###"(//.*(\r\n|\r|\n|$))"###,
        /*  4 */ UNMATCHABLE_TOKEN,
    ],
    &[
        5,  /* LookaheadDFA */
        6,  /* LBrace */
        7,  /* RBrace */
        8,  /* Integer */
        9,  /* SlashStar */
        10, /* Minus */
        11, /* StarSlash */
        12, /* Prod0 */
        13, /* Colon */
        14, /* Comma */
        15, /* Transitions */
        16, /* Amp */
        17, /* LBracket */
        18, /* RBracket */
        19, /* Trans */
        20, /* LParen */
        21, /* RParen */
        22, /* K */
        23, /* NtName */
    ],
);

const MAX_K: usize = 1;

pub const NON_TERMINALS: &[&str; 19] = &[
    /*  0 */ "CommaOpt",
    /*  1 */ "CommaOpt0",
    /*  2 */ "Integer",
    /*  3 */ "K",
    /*  4 */ "LaDfa2Dot",
    /*  5 */ "NamingComment",
    /*  6 */ "NtName",
    /*  7 */ "Parts",
    /*  8 */ "Prod0",
    /*  9 */ "TransEntry",
    /* 10 */ "TransEntryPostfix",
    /* 11 */ "TransEntryPrefix",
    /* 12 */ "TransEntryValue",
    /* 13 */ "TransList",
    /* 14 */ "TransListList",
    /* 15 */ "TransValues",
    /* 16 */ "Transitions",
    /* 17 */ "TransitionsPostfix",
    /* 18 */ "TransitionsPrefix",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 19] = &[
    /* 0 - "CommaOpt" */
    LookaheadDFA {
        prod0: 18,
        transitions: &[],
        k: 0,
    },
    /* 1 - "CommaOpt0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 20),
            Trans(0, 8, 2, 20),
            Trans(0, 14, 1, 19),
            Trans(0, 21, 2, 20),
            Trans(0, 22, 2, 20),
        ],
        k: 1,
    },
    /* 2 - "Integer" */
    LookaheadDFA {
        prod0: 2,
        transitions: &[],
        k: 0,
    },
    /* 3 - "K" */
    LookaheadDFA {
        prod0: 16,
        transitions: &[],
        k: 0,
    },
    /* 4 - "LaDfa2Dot" */
    LookaheadDFA {
        prod0: 0,
        transitions: &[],
        k: 0,
    },
    /* 5 - "NamingComment" */
    LookaheadDFA {
        prod0: 3,
        transitions: &[],
        k: 0,
    },
    /* 6 - "NtName" */
    LookaheadDFA {
        prod0: 17,
        transitions: &[],
        k: 0,
    },
    /* 7 - "Parts" */
    LookaheadDFA {
        prod0: 1,
        transitions: &[],
        k: 0,
    },
    /* 8 - "Prod0" */
    LookaheadDFA {
        prod0: 4,
        transitions: &[],
        k: 0,
    },
    /* 9 - "TransEntry" */
    LookaheadDFA {
        prod0: 15,
        transitions: &[],
        k: 0,
    },
    /* 10 - "TransEntryPostfix" */
    LookaheadDFA {
        prod0: 12,
        transitions: &[],
        k: 0,
    },
    /* 11 - "TransEntryPrefix" */
    LookaheadDFA {
        prod0: 11,
        transitions: &[],
        k: 0,
    },
    /* 12 - "TransEntryValue" */
    LookaheadDFA {
        prod0: 13,
        transitions: &[],
        k: 0,
    },
    /* 13 - "TransList" */
    LookaheadDFA {
        prod0: 8,
        transitions: &[],
        k: 0,
    },
    /* 14 - "TransListList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 18, 2, 10), Trans(0, 19, 1, 9)],
        k: 1,
    },
    /* 15 - "TransValues" */
    LookaheadDFA {
        prod0: 14,
        transitions: &[],
        k: 0,
    },
    /* 16 - "Transitions" */
    LookaheadDFA {
        prod0: 7,
        transitions: &[],
        k: 0,
    },
    /* 17 - "TransitionsPostfix" */
    LookaheadDFA {
        prod0: 6,
        transitions: &[],
        k: 0,
    },
    /* 18 - "TransitionsPrefix" */
    LookaheadDFA {
        prod0: 5,
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 21] = &[
    // 0 - LaDfa2Dot: NamingComment 'LookaheadDFA'^ /* Clipped */ Parts;
    Production {
        lhs: 4,
        production: &[ParseType::N(7), ParseType::T(5), ParseType::N(5)],
    },
    // 1 - Parts: '{'^ /* Clipped */ Prod0 Transitions K '}'^ /* Clipped */ CommaOpt^ /* Clipped */;
    Production {
        lhs: 7,
        production: &[
            ParseType::N(0),
            ParseType::T(7),
            ParseType::N(3),
            ParseType::N(16),
            ParseType::N(8),
            ParseType::T(6),
        ],
    },
    // 2 - Integer: /-?\d+/;
    Production {
        lhs: 2,
        production: &[ParseType::T(8)],
    },
    // 3 - NamingComment: "/\*"^ /* Clipped */ Integer '-'^ /* Clipped */ NtName "\*/"^ /* Clipped */;
    Production {
        lhs: 5,
        production: &[
            ParseType::T(11),
            ParseType::N(6),
            ParseType::T(10),
            ParseType::N(2),
            ParseType::T(9),
        ],
    },
    // 4 - Prod0: 'prod0'^ /* Clipped */ ':'^ /* Clipped */ Integer ','^ /* Clipped */;
    Production {
        lhs: 8,
        production: &[
            ParseType::T(14),
            ParseType::N(2),
            ParseType::T(13),
            ParseType::T(12),
        ],
    },
    // 5 - TransitionsPrefix: 'transitions'^ /* Clipped */ ':'^ /* Clipped */ '&'^ /* Clipped */ '['^ /* Clipped */;
    Production {
        lhs: 18,
        production: &[
            ParseType::T(17),
            ParseType::T(16),
            ParseType::T(13),
            ParseType::T(15),
        ],
    },
    // 6 - TransitionsPostfix: ']'^ /* Clipped */ CommaOpt^ /* Clipped */;
    Production {
        lhs: 17,
        production: &[ParseType::N(0), ParseType::T(18)],
    },
    // 7 - Transitions: TransitionsPrefix^ /* Clipped */ TransList TransitionsPostfix^ /* Clipped */;
    Production {
        lhs: 16,
        production: &[ParseType::N(17), ParseType::N(13), ParseType::N(18)],
    },
    // 8 - TransList: TransListList /* Vec */;
    Production {
        lhs: 13,
        production: &[ParseType::N(14)],
    },
    // 9 - TransListList: TransEntry TransListList;
    Production {
        lhs: 14,
        production: &[ParseType::N(14), ParseType::N(9)],
    },
    // 10 - TransListList: ;
    Production {
        lhs: 14,
        production: &[],
    },
    // 11 - TransEntryPrefix: 'Trans'^ /* Clipped */ '('^ /* Clipped */;
    Production {
        lhs: 11,
        production: &[ParseType::T(20), ParseType::T(19)],
    },
    // 12 - TransEntryPostfix: ')'^ /* Clipped */ ','^ /* Clipped */;
    Production {
        lhs: 10,
        production: &[ParseType::T(14), ParseType::T(21)],
    },
    // 13 - TransEntryValue: Integer CommaOpt^ /* Clipped */;
    Production {
        lhs: 12,
        production: &[ParseType::N(0), ParseType::N(2)],
    },
    // 14 - TransValues: TransEntryValue TransEntryValue TransEntryValue TransEntryValue;
    Production {
        lhs: 15,
        production: &[
            ParseType::N(12),
            ParseType::N(12),
            ParseType::N(12),
            ParseType::N(12),
        ],
    },
    // 15 - TransEntry: TransEntryPrefix^ /* Clipped */ TransValues TransEntryPostfix^ /* Clipped */;
    Production {
        lhs: 9,
        production: &[ParseType::N(10), ParseType::N(15), ParseType::N(11)],
    },
    // 16 - K: 'k'^ /* Clipped */ ':'^ /* Clipped */ Integer ','^ /* Clipped */;
    Production {
        lhs: 3,
        production: &[
            ParseType::T(14),
            ParseType::N(2),
            ParseType::T(13),
            ParseType::T(22),
        ],
    },
    // 17 - NtName: /"\w+?"/;
    Production {
        lhs: 6,
        production: &[ParseType::T(23)],
    },
    // 18 - CommaOpt: CommaOpt0 /* Option */;
    Production {
        lhs: 0,
        production: &[ParseType::N(1)],
    },
    // 19 - CommaOpt0: ','^ /* Clipped */;
    Production {
        lhs: 1,
        production: &[ParseType::T(14)],
    },
    // 20 - CommaOpt0: ;
    Production {
        lhs: 1,
        production: &[],
    },
];

static TOKENIZERS: Lazy<Vec<(&'static str, Tokenizer)>> = Lazy::new(|| {
    vec![(
        "INITIAL",
        Tokenizer::build(TERMINALS, SCANNER_0.0, SCANNER_0.1).unwrap(),
    )]
});

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut LaDfa2DotGrammar<'t>,
) -> Result<ParseTree<'t>, ParolError>
where
    T: AsRef<Path>,
{
    let mut llk_parser = LLKParser::new(
        4,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    llk_parser.trim_parse_tree();
    let token_stream =
        RefCell::new(TokenStream::new(input, file_name, &TOKENIZERS, MAX_K).unwrap());
    // Initialize wrapper
    let mut user_actions = LaDfa2DotGrammarAuto::new(user_actions);
    llk_parser.parse(token_stream, &mut user_actions)
}
